---
- name: Execute playbook development branch
  hosts: webservers  # Replace with the host/group name of the server(s)

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Install Git
      become: true
      apt:
        name: git
        state: present

    - name: Clone project from git repository
      git:
        repo: https://github.com/sokvotha/ansoble-learn.git  # Replace with the URL of the Git repository
        dest: /tmp/web-payment/  # Replace with the path where you want to clone the repository
        version: development  # Replace with the branch, tag, or commit you want to clone

    - name: Install nvm
      git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version=v0.33.11
      tags: nvm

    - name: Source nvm in ~/.{{ item }}
      lineinfile: >
          dest=~/.{{ item }}
          line="source ~/.nvm/nvm.sh"
          create=yes
      tags: nvm
      with_items:
        - bashrc
        - profile

    - name: Install node and set version
      become: yes
      become_user: root
      shell: "source /root/.nvm/nvm.sh && nvm install 14.15.0" 
      args:
        executable: /bin/bash

    # - name: Switch to node version 14
    #   become: true
    #   become_user: root
    #   shell: "source /root/.nvm/nvm.sh && nvm use 14" 
      # args:
      #   executable: /bin/bash

    # - name: Install Node.js
    #   become: true
    #   apt:
    #     name: nodejs
    #     state: present

    - name: Install npm package manager
      become: true
      apt:
        name: npm
        state: present

    - name: Install Angular CLI
      become: true
      npm:
        name: '@angular/cli@8'
        global: yes

    - name: Install @angular-devkit/build-angular
      become: true
      npm:
        name: '@angular-devkit/build-angular'
        global: yes

    - name: Install Angular Dependencies
      become: true
      command:  npm install
      args:
        chdir: /tmp/web-payment/
    # - name: Set directory permissions
    #   become: true
    #   file:
    #     path: /tmp/web-payment
    #     owner: root
    #     # group: <groupname>
    #     mode: '0755'

    - name: Execute Angular build command
      become: true
      command: ng build --prod
      args:
        chdir: /tmp/web-payment/

    # - name: Copy Angular build output to remote server
    #   command: cp -r /web-payment/dist/payment-demo /var/www/html
    #   when: state_labs.stat.exists
    - name: Copy Angular build output to remote server
      copy:
        src: /tmp/web-payment/dist/payment-demo/  # Replace with the path to the file inside the cloned repository
        dest: /var/www/html/payment-demo  # Replace with the path to the destination on the server
        remote_src: yes
